/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'name' : string, 'fields' : Array<CategoryField> }
export interface CategoryField {
  'name' : string,
  'options' : Array<string>,
  'fieldType' : string,
}
export interface ColumnDef { 'name' : string, 'colType' : string }
export interface CustomColumns {
  'transit' : Array<ColumnDef>,
  'inward' : Array<ColumnDef>,
  'warehouse' : Array<ColumnDef>,
}
export interface GodownStock { 'name' : string, 'quantity' : bigint }
export interface InventoryItem {
  'sku' : string,
  'businessId' : string,
  'purchaseRate' : number,
  'shop' : bigint,
  'minThreshold' : [] | [bigint],
  'attributes' : Array<[string, string]>,
  'itemName' : string,
  'category' : string,
  'godowns' : Array<GodownStock>,
  'saleRate' : number,
}
export interface PendingParcel {
  'id' : bigint,
  'businessId' : string,
  'packages' : string,
  'biltyNo' : string,
  'dateReceived' : string,
  'customData' : Array<[string, string]>,
  'transportName' : string,
}
export interface Settings {
  'biltyPrefixes' : Array<string>,
  'minStockThreshold' : bigint,
  'godowns' : Array<string>,
}
export interface StockDelta {
  'shopDelta' : bigint,
  'godownDeltas' : Array<GodownStock>,
}
export interface StockTransfer {
  'to' : string,
  'from' : string,
  'quantity' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'businessId' : string,
  'role' : UserRole,
  'isActive' : boolean,
  'registered' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'supplier' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, Array<CategoryField>], undefined>,
  'addStock' : ActorMethod<[string, StockDelta], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCustomColumns' : ActorMethod<[], CustomColumns>,
  'getInventorySortedByPurchaseRate' : ActorMethod<[], Array<InventoryItem>>,
  'getInventorySortedBySaleRate' : ActorMethod<[], Array<InventoryItem>>,
  'getInventorySortedByShopStock' : ActorMethod<[], Array<InventoryItem>>,
  'getInventorySortedBySku' : ActorMethod<[], Array<InventoryItem>>,
  'getPendingParcels' : ActorMethod<[], Array<PendingParcel>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[Principal, string, string, UserRole], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCustomColumns' : ActorMethod<[CustomColumns], undefined>,
  'setSettings' : ActorMethod<[Settings], undefined>,
  'transferStock' : ActorMethod<[StockTransfer], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];