/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryField = IDL.Record({
  'name' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'fieldType' : IDL.Text,
});
export const GodownStock = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Int,
});
export const StockDelta = IDL.Record({
  'shopDelta' : IDL.Int,
  'godownDeltas' : IDL.Vec(GodownStock),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'fields' : IDL.Vec(CategoryField),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'supplier' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'businessId' : IDL.Text,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'registered' : Time,
});
export const ColumnDef = IDL.Record({
  'name' : IDL.Text,
  'colType' : IDL.Text,
});
export const CustomColumns = IDL.Record({
  'transit' : IDL.Vec(ColumnDef),
  'inward' : IDL.Vec(ColumnDef),
  'warehouse' : IDL.Vec(ColumnDef),
});
export const InventoryItem = IDL.Record({
  'sku' : IDL.Text,
  'businessId' : IDL.Text,
  'purchaseRate' : IDL.Float64,
  'shop' : IDL.Int,
  'minThreshold' : IDL.Opt(IDL.Int),
  'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'itemName' : IDL.Text,
  'category' : IDL.Text,
  'godowns' : IDL.Vec(GodownStock),
  'saleRate' : IDL.Float64,
});
export const PendingParcel = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : IDL.Text,
  'packages' : IDL.Text,
  'biltyNo' : IDL.Text,
  'dateReceived' : IDL.Text,
  'customData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'transportName' : IDL.Text,
});
export const Settings = IDL.Record({
  'biltyPrefixes' : IDL.Vec(IDL.Text),
  'minStockThreshold' : IDL.Int,
  'godowns' : IDL.Vec(IDL.Text),
});
export const StockTransfer = IDL.Record({
  'to' : IDL.Text,
  'from' : IDL.Text,
  'quantity' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Vec(CategoryField)], [], []),
  'addStock' : IDL.Func([IDL.Text, StockDelta], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCustomColumns' : IDL.Func([], [CustomColumns], ['query']),
  'getInventorySortedByPurchaseRate' : IDL.Func(
      [],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getInventorySortedBySaleRate' : IDL.Func(
      [],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getInventorySortedByShopStock' : IDL.Func(
      [],
      [IDL.Vec(InventoryItem)],
      ['query'],
    ),
  'getInventorySortedBySku' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getPendingParcels' : IDL.Func([], [IDL.Vec(PendingParcel)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text, UserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCustomColumns' : IDL.Func([CustomColumns], [], []),
  'setSettings' : IDL.Func([Settings], [], []),
  'transferStock' : IDL.Func([StockTransfer], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryField = IDL.Record({
    'name' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'fieldType' : IDL.Text,
  });
  const GodownStock = IDL.Record({ 'name' : IDL.Text, 'quantity' : IDL.Int });
  const StockDelta = IDL.Record({
    'shopDelta' : IDL.Int,
    'godownDeltas' : IDL.Vec(GodownStock),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'name' : IDL.Text,
    'fields' : IDL.Vec(CategoryField),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'supplier' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'businessId' : IDL.Text,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'registered' : Time,
  });
  const ColumnDef = IDL.Record({ 'name' : IDL.Text, 'colType' : IDL.Text });
  const CustomColumns = IDL.Record({
    'transit' : IDL.Vec(ColumnDef),
    'inward' : IDL.Vec(ColumnDef),
    'warehouse' : IDL.Vec(ColumnDef),
  });
  const InventoryItem = IDL.Record({
    'sku' : IDL.Text,
    'businessId' : IDL.Text,
    'purchaseRate' : IDL.Float64,
    'shop' : IDL.Int,
    'minThreshold' : IDL.Opt(IDL.Int),
    'attributes' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'itemName' : IDL.Text,
    'category' : IDL.Text,
    'godowns' : IDL.Vec(GodownStock),
    'saleRate' : IDL.Float64,
  });
  const PendingParcel = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : IDL.Text,
    'packages' : IDL.Text,
    'biltyNo' : IDL.Text,
    'dateReceived' : IDL.Text,
    'customData' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'transportName' : IDL.Text,
  });
  const Settings = IDL.Record({
    'biltyPrefixes' : IDL.Vec(IDL.Text),
    'minStockThreshold' : IDL.Int,
    'godowns' : IDL.Vec(IDL.Text),
  });
  const StockTransfer = IDL.Record({
    'to' : IDL.Text,
    'from' : IDL.Text,
    'quantity' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Vec(CategoryField)], [], []),
    'addStock' : IDL.Func([IDL.Text, StockDelta], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCustomColumns' : IDL.Func([], [CustomColumns], ['query']),
    'getInventorySortedByPurchaseRate' : IDL.Func(
        [],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getInventorySortedBySaleRate' : IDL.Func(
        [],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getInventorySortedByShopStock' : IDL.Func(
        [],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getInventorySortedBySku' : IDL.Func(
        [],
        [IDL.Vec(InventoryItem)],
        ['query'],
      ),
    'getPendingParcels' : IDL.Func([], [IDL.Vec(PendingParcel)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, UserRole],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCustomColumns' : IDL.Func([CustomColumns], [], []),
    'setSettings' : IDL.Func([Settings], [], []),
    'transferStock' : IDL.Func([StockTransfer], [], []),
  });
};

export const init = ({ IDL }) => { return []; };